name: Nightly

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger TestFlight build
        run: |
          gh workflow run testflight.yml --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
